name: Push to Replicate

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Cog
        run: |
          curl -o cog -L https://github.com/replicate/cog/releases/download/v0.14.0/cog_Linux_x86_64
          chmod +x cog
          sudo mv cog /usr/local/bin/cog

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog push r8.im/maqbool1610/matchmind-compatibility
